#coding: utf-8
#
# Dict of well-known and reserved TCP ports, per RFC1340, available here:
#   https://tools.ietf.org/html/rfc1340
#
# I manually clipped out pages 7 through 21 inclusive, and manually deleted
# the page headers and footers, and saved this in a file I called "rfc1340".
#
# Then I ran this command to extract TCP port numbers, keywords and
# descriptions and put them into a JSON format (and manually edited out
# the comma after the last element in the array).
#
# echo "{"; grep '/tcp' rfc1340 | egrep -v '/tcp    Unassigned|/tcp    Reserved' | sed 's/^                    /   none             /;s/\/tcp    /     /;s/\[.*\]$//' | awk '{ printf "  %d: { \"keyword\": \"%s\", \"description\": \"%s", $2, $1, $3; for (i=4; i<=NF; i++) { printf " %s", $i; } printf "\" },\n"; }' ; echo "}"
#
# Entries with missing keywords are given keyword, "none".
# Entries with missing description are given description, "".
#
# Written by Glen Darling, May 2019.
#

known_tcp_ports = {

  # --------------------
  # Well-Known TCP Ports
  # --------------------

  1: { "keyword": "tcpmux", "description": "TCP Port Service Multiplexer" },
  2: { "keyword": "compressnet", "description": "Management Utility" },
  3: { "keyword": "compressnet", "description": "Compression Process" },
  5: { "keyword": "rje", "description": "Remote Job Entry" },
  7: { "keyword": "echo", "description": "Echo" },
  9: { "keyword": "discard", "description": "Discard" },
  11: { "keyword": "systat", "description": "Active Users" },
  13: { "keyword": "daytime", "description": "Daytime" },
  17: { "keyword": "qotd", "description": "Quote of the Day" },
  18: { "keyword": "msp", "description": "Message Send Protocol" },
  19: { "keyword": "chargen", "description": "Character Generator" },
  20: { "keyword": "ftp-data", "description": "File Transfer" },
  21: { "keyword": "ftp", "description": "File Transfer" },
  23: { "keyword": "telnet", "description": "Telnet" },
  24: { "keyword": "none", "description": "any private mail system" },
  25: { "keyword": "smtp", "description": "Simple Mail Transfer" },
  27: { "keyword": "nsw-fe", "description": "NSW User System FE" },
  29: { "keyword": "msg-icp", "description": "MSG ICP" },
  31: { "keyword": "msg-auth", "description": "MSG Authentication" },
  33: { "keyword": "dsp", "description": "Display Support Protocol" },
  35: { "keyword": "none", "description": "any private printer server" },
  37: { "keyword": "time", "description": "Time" },
  39: { "keyword": "rlp", "description": "Resource Location Protocol" },
  41: { "keyword": "graphics", "description": "Graphics" },
  42: { "keyword": "nameserver", "description": "Host Name Server" },
  43: { "keyword": "nicname", "description": "Who Is" },
  44: { "keyword": "mpm-flags", "description": "MPM FLAGS Protocol" },
  45: { "keyword": "mpm", "description": "Message Processing Module" },
  46: { "keyword": "mpm-snd", "description": "MPM" },
  47: { "keyword": "ni-ftp", "description": "NI FTP" },
  49: { "keyword": "login", "description": "Login Host Protocol" },
  50: { "keyword": "re-mail-ck", "description": "Remote Mail Checking Protocol" },
  51: { "keyword": "la-maint", "description": "IMP Logical Address Maintenance" },
  52: { "keyword": "xns-time", "description": "XNS Time Protocol" },
  53: { "keyword": "domain", "description": "Domain Name Server" },
  54: { "keyword": "xns-ch", "description": "XNS Clearinghouse" },
  55: { "keyword": "isi-gl", "description": "ISI Graphics Language" },
  56: { "keyword": "xns-auth", "description": "XNS Authentication" },
  57: { "keyword": "none", "description": "any private terminal access" },
  58: { "keyword": "xns-mail", "description": "XNS Mail" },
  59: { "keyword": "none", "description": "any private file service" },
  61: { "keyword": "ni-mail", "description": "NI MAIL" },
  62: { "keyword": "acas", "description": "ACA Services" },
  63: { "keyword": "via-ftp", "description": "VIA Systems - FTP" },
  64: { "keyword": "covia", "description": "Communications Integrator (CI)" },
  65: { "keyword": "tacacs-ds", "description": "TACACS-Database Service" },
  66: { "keyword": "sql*net", "description": "Oracle SQL*NET" },
  67: { "keyword": "bootps", "description": "Bootstrap Protocol Server" },
  68: { "keyword": "bootpc", "description": "Bootstrap Protocol Client" },
  69: { "keyword": "tftp", "description": "Trivial File Transfer" },
  70: { "keyword": "gopher", "description": "Gopher" },
  71: { "keyword": "netrjs-1", "description": "Remote Job Service" },
  72: { "keyword": "netrjs-2", "description": "Remote Job Service" },
  73: { "keyword": "netrjs-3", "description": "Remote Job Service" },
  74: { "keyword": "netrjs-4", "description": "Remote Job Service" },
  75: { "keyword": "none", "description": "any private dial out service" },
  77: { "keyword": "none", "description": "any private RJE service" },
  78: { "keyword": "vettcp", "description": "vettcp" },
  79: { "keyword": "finger", "description": "Finger" },
  80: { "keyword": "www", "description": "World Wide Web HTTP" },
  81: { "keyword": "hosts2-ns", "description": "HOSTS2 Name Server" },
  82: { "keyword": "xfer", "description": "XFER Utility" },
  83: { "keyword": "mit-ml-dev", "description": "MIT ML Device" },
  84: { "keyword": "ctf", "description": "Common Trace Facility" },
  85: { "keyword": "mit-ml-dev", "description": "MIT ML Device" },
  86: { "keyword": "mfcobol", "description": "Micro Focus Cobol" },
  87: { "keyword": "none", "description": "any private terminal link" },
  88: { "keyword": "kerberos", "description": "Kerberos" },
  89: { "keyword": "su-mit-tg", "description": "SU/MIT Telnet Gateway" },
  90: { "keyword": "dnsix", "description": "DNSIX Securit Attribute Token Map" },
  91: { "keyword": "mit-dov", "description": "MIT Dover Spooler" },
  92: { "keyword": "npp", "description": "Network Printing Protocol" },
  93: { "keyword": "dcp", "description": "Device Control Protocol" },
  94: { "keyword": "objcall", "description": "Tivoli Object Dispatcher" },
  95: { "keyword": "supdup", "description": "SUPDUP" },
  96: { "keyword": "dixie", "description": "DIXIE Protocol Specification" },
  97: { "keyword": "swift-rvf", "description": "Swift Remote Vitural File Protocol" },
  98: { "keyword": "tacnews", "description": "TAC News" },
  99: { "keyword": "metagram", "description": "Metagram Relay" },
  100: { "keyword": "newacct", "description": "" },
  101: { "keyword": "hostname", "description": "NIC Host Name Server" },
  102: { "keyword": "iso-tsap", "description": "ISO-TSAP" },
  103: { "keyword": "gppitnp", "description": "Genesis Point-to-Point Trans Net" },
  104: { "keyword": "acr-nema", "description": "ACR-NEMA Digital Imag. & Comm. 300" },
  105: { "keyword": "csnet-ns", "description": "Mailbox Name Nameserver" },
  106: { "keyword": "3com-tsmux", "description": "3COM-TSMUX" },
  107: { "keyword": "rtelnet", "description": "Remote Telnet Service" },
  108: { "keyword": "snagas", "description": "SNA Gateway Access Server" },
  109: { "keyword": "pop2", "description": "Post Office Protocol - Version 2" },
  110: { "keyword": "pop3", "description": "Post Office Protocol - Version 3" },
  111: { "keyword": "sunrpc", "description": "SUN Remote Procedure Call" },
  112: { "keyword": "mcidas", "description": "McIDAS Data Transmission Protocol" },
  113: { "keyword": "auth", "description": "Authentication Service" },
  114: { "keyword": "audionews", "description": "Audio News Multicast" },
  115: { "keyword": "sftp", "description": "Simple File Transfer Protocol" },
  116: { "keyword": "ansanotify", "description": "ANSA REX Notify" },
  117: { "keyword": "uucp-path", "description": "UUCP Path Service" },
  118: { "keyword": "sqlserv", "description": "SQL Services" },
  119: { "keyword": "nntp", "description": "Network News Transfer Protocol" },
  120: { "keyword": "cfdptkt", "description": "CFDPTKT" },
  121: { "keyword": "erpc", "description": "Encore Expedited Remote Pro.Call" },
  122: { "keyword": "smakynet", "description": "SMAKYNET" },
  123: { "keyword": "ntp", "description": "Network Time Protocol" },
  124: { "keyword": "ansatrader", "description": "ANSA REX Trader" },
  125: { "keyword": "locus-map", "description": "Locus PC-Interface Net Map Ser" },
  126: { "keyword": "unitary", "description": "Unisys Unitary Login" },
  127: { "keyword": "locus-con", "description": "Locus PC-Interface Conn Server" },
  128: { "keyword": "gss-xlicen", "description": "GSS X License Verification" },
  129: { "keyword": "pwdgen", "description": "Password Generator Protocol" },
  130: { "keyword": "cisco-fna", "description": "cisco FNATIVE" },
  131: { "keyword": "cisco-tna", "description": "cisco TNATIVE" },
  132: { "keyword": "cisco-sys", "description": "cisco SYSMAINT" },
  133: { "keyword": "statsrv", "description": "Statistics Service" },
  134: { "keyword": "ingres-net", "description": "INGRES-NET Service" },
  135: { "keyword": "loc-srv", "description": "Location Service" },
  136: { "keyword": "profile", "description": "PROFILE Naming System" },
  137: { "keyword": "netbios-ns", "description": "NETBIOS Name Service" },
  138: { "keyword": "netbios-dgm", "description": "NETBIOS Datagram Service" },
  139: { "keyword": "netbios-ssn", "description": "NETBIOS Session Service" },
  140: { "keyword": "emfis-data", "description": "EMFIS Data Service" },
  141: { "keyword": "emfis-cntl", "description": "EMFIS Control Service" },
  142: { "keyword": "bl-idm", "description": "Britton-Lee IDM" },
  143: { "keyword": "imap2", "description": "Interim Mail Access Protocol v2" },
  144: { "keyword": "news", "description": "NewS" },
  145: { "keyword": "uaac", "description": "UAAC Protocol" },
  146: { "keyword": "iso-tp0", "description": "ISO-IP0" },
  147: { "keyword": "iso-ip", "description": "ISO-IP" },
  148: { "keyword": "cronus", "description": "CRONUS-SUPPORT" },
  149: { "keyword": "aed-512", "description": "AED 512 Emulation Service" },
  150: { "keyword": "sql-net", "description": "SQL-NET" },
  151: { "keyword": "hems", "description": "HEMS" },
  152: { "keyword": "bftp", "description": "Background File Transfer Program" },
  153: { "keyword": "sgmp", "description": "SGMP" },
  154: { "keyword": "netsc-prod", "description": "NETSC" },
  155: { "keyword": "netsc-dev", "description": "NETSC" },
  156: { "keyword": "sqlsrv", "description": "SQL Service" },
  157: { "keyword": "knet-cmp", "description": "KNET/VM Command/Message Protocol" },
  158: { "keyword": "pcmail-srv", "description": "PCMail Server" },
  159: { "keyword": "nss-routing", "description": "NSS-Routing" },
  160: { "keyword": "sgmp-traps", "description": "SGMP-TRAPS" },
  161: { "keyword": "snmp", "description": "SNMP" },
  162: { "keyword": "snmptrap", "description": "SNMPTRAP" },
  163: { "keyword": "cmip-man", "description": "CMIP/TCP Manager" },
  164: { "keyword": "cmip-agent", "description": "CMIP/TCP Agent" },
  165: { "keyword": "xns-courier", "description": "Xerox 144,SXA]" },
  166: { "keyword": "s-net", "description": "Sirius Systems" },
  167: { "keyword": "namp", "description": "NAMP" },
  168: { "keyword": "rsvd", "description": "RSVD" },
  169: { "keyword": "send", "description": "SEND" },
  170: { "keyword": "print-srv", "description": "Network PostScript" },
  171: { "keyword": "multiplex", "description": "Network Innovations Multiplex" },
  172: { "keyword": "cl/1", "description": "Network Innovations CL/1" },
  173: { "keyword": "xyplex-mux", "description": "Xyplex" },
  174: { "keyword": "mailq", "description": "MAILQ" },
  175: { "keyword": "vmnet", "description": "VMNET" },
  176: { "keyword": "genrad-mux", "description": "GENRAD-MUX" },
  177: { "keyword": "xdmcp", "description": "X Display Manager Control Protocol" },
  178: { "keyword": "nextstep", "description": "NextStep Window Server" },
  179: { "keyword": "bgp", "description": "Border Gateway Protocol" },
  180: { "keyword": "ris", "description": "Intergraph" },
  181: { "keyword": "unify", "description": "Unify" },
  182: { "keyword": "audit", "description": "Unisys Audit SITP" },
  183: { "keyword": "ocbinder", "description": "OCBinder" },
  184: { "keyword": "ocserver", "description": "OCServer" },
  185: { "keyword": "remote-kis", "description": "Remote-KIS" },
  186: { "keyword": "kis", "description": "KIS Protocol" },
  187: { "keyword": "aci", "description": "Application Communication Interface" },
  188: { "keyword": "mumps", "description": "Plus Five's MUMPS" },
  189: { "keyword": "qft", "description": "Queued File Transport" },
  190: { "keyword": "gacp", "description": "Gateway Access Control Protocol" },
  191: { "keyword": "prospero", "description": "Prospero" },
  192: { "keyword": "osu-nms", "description": "OSU Network Monitoring System" },
  193: { "keyword": "srmp", "description": "Spider Remote Monitoring Protocol" },
  194: { "keyword": "irc", "description": "Internet Relay Chat Protocol" },
  195: { "keyword": "dn6-nlm-aud", "description": "DNSIX Network Level Module Audit" },
  196: { "keyword": "dn6-smm-red", "description": "DNSIX Session Mgt Module Audit Redir" },
  197: { "keyword": "dls", "description": "Directory Location Service" },
  198: { "keyword": "dls-mon", "description": "Directory Location Service Monitor" },
  199: { "keyword": "smux", "description": "SMUX" },
  200: { "keyword": "src", "description": "IBM System Resource Controller" },
  201: { "keyword": "at-rtmp", "description": "AppleTalk Routing Maintenance" },
  202: { "keyword": "at-nbp", "description": "AppleTalk Name Binding" },
  203: { "keyword": "at-3", "description": "AppleTalk Unused" },
  204: { "keyword": "at-echo", "description": "AppleTalk Echo" },
  205: { "keyword": "at-5", "description": "AppleTalk Unused" },
  206: { "keyword": "at-zis", "description": "AppleTalk Zone Information" },
  207: { "keyword": "at-7", "description": "AppleTalk Unused" },
  208: { "keyword": "at-8", "description": "AppleTalk Unused" },
  209: { "keyword": "tam", "description": "Trivial Authenticated Mail Protocol" },
  210: { "keyword": "z39.50", "description": "ANSI Z39.50" },
  211: { "keyword": "914c/g", "description": "Texas Instruments 914C/G Terminal" },
  212: { "keyword": "anet", "description": "ATEXSSTR" },
  213: { "keyword": "ipx", "description": "IPX" },
  214: { "keyword": "vmpwscs", "description": "VM PWSCS" },
  215: { "keyword": "softpc", "description": "Insignia Solutions" },
  216: { "keyword": "atls", "description": "Access Technology License Server" },
  217: { "keyword": "dbase", "description": "dBASE Unix" },
  218: { "keyword": "mpp", "description": "Netix Message Posting Protocol" },
  219: { "keyword": "uarps", "description": "Unisys ARPs" },
  220: { "keyword": "imap3", "description": "Interactive Mail Access Protocol v3" },
  221: { "keyword": "fln-spx", "description": "Berkeley rlogind with SPX auth" },
  222: { "keyword": "fsh-spx", "description": "Berkeley rshd with SPX auth" },
  223: { "keyword": "cdc", "description": "Certificate Distribution Center" },
  243: { "keyword": "sur-meas", "description": "Survey Measurement" },
  245: { "keyword": "link", "description": "LINK" },
  246: { "keyword": "dsp3270", "description": "Display Systems Protocol" },
  345: { "keyword": "pawserv", "description": "Perf Analysis Workbench" },
  346: { "keyword": "zserv", "description": "Zebra server" },
  347: { "keyword": "fatserv", "description": "Fatmen Server" },
  371: { "keyword": "clearcase", "description": "Clearcase" },
  372: { "keyword": "ulistserv", "description": "Unix Listserv" },
  373: { "keyword": "legent-1", "description": "Legent Corporation" },
  374: { "keyword": "legent-2", "description": "Legent Corporation" },
  512: { "keyword": "exec", "description": "remote process execution;" },
  513: { "keyword": "login", "description": "remote login a la telnet;" },
  514: { "keyword": "cmd", "description": "like exec, but automatic" },
  515: { "keyword": "printer", "description": "spooler" },
  517: { "keyword": "talk", "description": "like tenex link, but across" },
  518: { "keyword": "ntalk", "description": "" },
  519: { "keyword": "utime", "description": "unixtime" },
  520: { "keyword": "efs", "description": "extended file name server" },
  525: { "keyword": "timed", "description": "timeserver" },
  526: { "keyword": "tempo", "description": "newdate" },
  530: { "keyword": "courier", "description": "rpc" },
  531: { "keyword": "conference", "description": "chat" },
  532: { "keyword": "netnews", "description": "readnews" },
  533: { "keyword": "netwall", "description": "for emergency broadcasts" },
  540: { "keyword": "uucp", "description": "uucpd" },
  543: { "keyword": "klogin", "description": "" },
  544: { "keyword": "kshell", "description": "krcmd" },
  550: { "keyword": "new-rwho", "description": "new-who" },
  555: { "keyword": "dsf", "description": "" },
  556: { "keyword": "remotefs", "description": "rfs server" },
  560: { "keyword": "rmonitor", "description": "rmonitord" },
  561: { "keyword": "monitor", "description": "" },
  562: { "keyword": "chshell", "description": "chcmd" },
  564: { "keyword": "9pfs", "description": "plan 9 file service" },
  565: { "keyword": "whoami", "description": "whoami" },
  570: { "keyword": "meter", "description": "demon" },
  571: { "keyword": "meter", "description": "udemon" },
  600: { "keyword": "ipcserver", "description": "Sun IPC server" },
  607: { "keyword": "nqs", "description": "nqs" },
  666: { "keyword": "mdqs", "description": "" },
  704: { "keyword": "elcsd", "description": "errlog copy/server daemon" },
  740: { "keyword": "netcp", "description": "NETscout Control Protocol" },
  741: { "keyword": "netgw", "description": "netGW" },
  742: { "keyword": "netrcs", "description": "Network based Rev. Cont. Sys." },
  744: { "keyword": "flexlm", "description": "Flexible License Manager" },
  747: { "keyword": "fujitsu-dev", "description": "Fujitsu Device Control" },
  748: { "keyword": "ris-cm", "description": "Russell Info Sci Calendar Manager" },
  749: { "keyword": "kerberos-adm", "description": "kerberos administration" },
  750: { "keyword": "rfile", "description": "" },
  751: { "keyword": "pump", "description": "" },
  752: { "keyword": "qrh", "description": "" },
  753: { "keyword": "rrh", "description": "" },
  754: { "keyword": "tell", "description": "send" },
  758: { "keyword": "nlogin", "description": "" },
  759: { "keyword": "con", "description": "" },
  760: { "keyword": "ns", "description": "" },
  761: { "keyword": "rxe", "description": "" },
  762: { "keyword": "quotad", "description": "" },
  763: { "keyword": "cycleserv", "description": "" },
  764: { "keyword": "omserv", "description": "" },
  765: { "keyword": "webster", "description": "" },
  767: { "keyword": "phonebook", "description": "phone" },
  769: { "keyword": "vid", "description": "" },
  770: { "keyword": "cadlock", "description": "" },
  771: { "keyword": "rtip", "description": "" },
  772: { "keyword": "cycleserv2", "description": "" },
  773: { "keyword": "submit", "description": "" },
  774: { "keyword": "rpasswd", "description": "" },
  775: { "keyword": "entomb", "description": "" },
  776: { "keyword": "wpages", "description": "" },
  780: { "keyword": "wpgs", "description": "" },
  781: { "keyword": "hp-collector", "description": "hp performance data collector" },
  782: { "keyword": "hp-managed-node", "description": "hp performance data managed node" },
  783: { "keyword": "hp-alarm-mgr", "description": "hp performance data alarm manager" },
  800: { "keyword": "mdbs_daemon", "description": "" },
  801: { "keyword": "device", "description": "" },
  996: { "keyword": "xtreelic", "description": "XTREE License Server" },
  997: { "keyword": "maitrd", "description": "" },
  998: { "keyword": "busboy", "description": "" },
  999: { "keyword": "garcon", "description": "" },
  999: { "keyword": "puprouter", "description": "" },
  1000: { "keyword": "cadlock", "description": "" },

  # -------------------------
  # IANA Registered TCP Ports
  # -------------------------

  1025: { "keyword": "blackjack", "description": "network blackjack" },
  1248: { "keyword": "hermes", "description": "" },
  1347: { "keyword": "bbn-mmc", "description": "multi media conferencing" },
  1348: { "keyword": "bbn-mmx", "description": "multi media conferencing" },
  1349: { "keyword": "sbook", "description": "Registration Network Protocol" },
  1350: { "keyword": "editbench", "description": "Registration Network Protocol" },
  1351: { "keyword": "equationbuilder", "description": "Digital Tool Works (MIT)" },
  1352: { "keyword": "lotusnote", "description": "Lotus Note" },
  1524: { "keyword": "ingreslock", "description": "ingres" },
  1525: { "keyword": "orasrv", "description": "oracle" },
  1525: { "keyword": "prospero-np", "description": "prospero non-privileged" },
  1527: { "keyword": "tlisrv", "description": "oracle" },
  1529: { "keyword": "coauthor", "description": "oracle" },
  1600: { "keyword": "issd", "description": "" },
  1650: { "keyword": "nkd", "description": "" },
  2000: { "keyword": "callbook", "description": "" },
  2001: { "keyword": "dc", "description": "" },
  2002: { "keyword": "globe", "description": "" },
  2004: { "keyword": "mailbox", "description": "" },
  2005: { "keyword": "berknet", "description": "" },
  2006: { "keyword": "invokator", "description": "" },
  2007: { "keyword": "dectalk", "description": "" },
  2008: { "keyword": "conf", "description": "" },
  2009: { "keyword": "news", "description": "" },
  2010: { "keyword": "search", "description": "" },
  2011: { "keyword": "raid-cc", "description": "raid" },
  2012: { "keyword": "ttyinfo", "description": "" },
  2013: { "keyword": "raid-am", "description": "" },
  2014: { "keyword": "troff", "description": "" },
  2015: { "keyword": "cypress", "description": "" },
  2016: { "keyword": "bootserver", "description": "" },
  2017: { "keyword": "cypress-stat", "description": "" },
  2018: { "keyword": "terminaldb", "description": "" },
  2019: { "keyword": "whosockami", "description": "" },
  2020: { "keyword": "xinupageserver", "description": "" },
  2021: { "keyword": "servexec", "description": "" },
  2022: { "keyword": "down", "description": "" },
  2023: { "keyword": "xinuexpansion3", "description": "" },
  2024: { "keyword": "xinuexpansion4", "description": "" },
  2025: { "keyword": "ellpack", "description": "" },
  2026: { "keyword": "scrabble", "description": "" },
  2027: { "keyword": "shadowserver", "description": "" },
  2028: { "keyword": "submitserver", "description": "" },
  2030: { "keyword": "device2", "description": "" },
  2032: { "keyword": "blackboard", "description": "" },
  2033: { "keyword": "glogger", "description": "" },
  2034: { "keyword": "scoremgr", "description": "" },
  2035: { "keyword": "imsldoc", "description": "" },
  2038: { "keyword": "objectmanager", "description": "" },
  2040: { "keyword": "lam", "description": "" },
  2041: { "keyword": "interbase", "description": "" },
  2042: { "keyword": "isis", "description": "" },
  2043: { "keyword": "isis-bcast", "description": "" },
  2044: { "keyword": "rimsl", "description": "" },
  2045: { "keyword": "cdfunc", "description": "" },
  2046: { "keyword": "sdfunc", "description": "" },
  2047: { "keyword": "dls", "description": "" },
  2048: { "keyword": "dls-monitor", "description": "" },
  2049: { "keyword": "shilp", "description": "" },
  2784: { "keyword": "www-dev", "description": "world wide web - development" },
  3049: { "keyword": "NSWS", "description": "" },
  4672: { "keyword": "rfa", "description": "remote file access server" },
  5000: { "keyword": "commplex-main", "description": "" },
  5001: { "keyword": "commplex-link", "description": "" },
  5002: { "keyword": "rfe", "description": "radio free ethernet" },
  5145: { "keyword": "rmonitor_secure", "description": "" },
  5236: { "keyword": "padl2sim", "description": "" },
  6111: { "keyword": "sub-process", "description": "HP SoftBench Sub-Process Control" },
  6558: { "keyword": "xdsxdm", "description": "" },
  7000: { "keyword": "afs3-fileserver", "description": "file server itself" },
  7001: { "keyword": "afs3-callback", "description": "callbacks to cache managers" },
  7002: { "keyword": "afs3-prserver", "description": "users & groups database" },
  7003: { "keyword": "afs3-vlserver", "description": "volume location database" },
  7004: { "keyword": "afs3-kaserver", "description": "AFS/Kerberos authentication service" },
  7005: { "keyword": "afs3-volser", "description": "volume managment server" },
  7006: { "keyword": "afs3-errors", "description": "error interpretation service" },
  7007: { "keyword": "afs3-bos", "description": "basic overseer process" },
  7008: { "keyword": "afs3-update", "description": "server-to-server updater" },
  7009: { "keyword": "afs3-rmtsys", "description": "remote cache manager service" },
  9535: { "keyword": "man", "description": "" },
  17007: { "keyword": "isode-dua", "description": "" }

}

